version: "3.8"

services:
  app:
    build: "."
    volumes:
      - .:/usr/src
    links: 
      - db
    depends_on:
      - db
    command: ["python", "main.py"]

  db:
    image: mysql
    ports:
      - "33060:3306"
    expose: 
      - "3306"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: users